version: "3.9"

services:
  mongo:
    image: mongo:8
    container_name: ecommerce-mongo

    restart: unless-stopped

    networks:
      - ecommerce-network

    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./Backend

    container_name: ecommerce-backend

    restart: unless-stopped

    env_file:
      - ./Backend/.env

    ports:
      - "5000:5000"

    depends_on:
      - mongo

    networks:
      - ecommerce-network

    volumes:
      - logs-data:/app/logs
      - uploads-data:/app/uploads

  redis:
    image: redis:7-alpine

    container_name: ecommerce-redis

    restart: unless-stopped

    networks:
      - ecommerce-network

    volumes:
      - redis-data:/data

  frontend:
    build:
      context: ./Frontend

    container_name: ecommerce-frontend

    restart: unless-stopped

    ports:
      - "5173:5173"

    networks:
      - ecommerce-network

    volumes:
      - ./Frontend:/app
      - /app/node_modules

    depends_on:
      - backend

networks:
  ecommerce-network:

volumes:
  mongo-data:
  logs-data:
  uploads-data:
  redis-data:
